# Generated by Django 3.1.7 on 2021-03-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210301_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestarticles',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='latestarticles',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='latestarticles',
            name='source',
        ),
        migrations.RemoveField(
            model_name='latestarticles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='latestarticles',
            name='updated_at',
        ),
    ]
