# Generated by Django 3.1.7 on 2021-03-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210301_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestarticles',
            name='guid',
        ),
        migrations.AddField(
            model_name='latestarticles',
            name='article_list',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
