# Generated by Django 3.1.7 on 2021-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_delete_latestarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_list', models.TextField(max_length=1024, null=True)),
            ],
        ),
    ]
