# Generated by Django 3.1.7 on 2021-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210301_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestarticles',
            name='article_list',
            field=models.TextField(default=' '),
        ),
    ]
