# Generated by Django 3.1.7 on 2021-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20210301_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment_magnitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='latestarticles',
            name='article_list',
            field=models.TextField(default=''),
        ),
    ]
