# Generated by Django 3.1.7 on 2021-03-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20210302_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestarticles',
            name='article_list',
            field=models.TextField(default='New LatestArticles List'),
        ),
    ]
