# Generated by Django 3.1.7 on 2021-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20210302_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
