# Generated by Django 3.1.7 on 2021-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
